/** @type {import('tailwindcss').Config} */
const colors = require('tailwindcss/colors')

module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      // dark: "#1A1B26",
      // darker: "#1A1C26",
      // dusk: "#565F89",
      // carolina: "#7897DA",
      // lavender: "#79459A",
      // purple: "#BB9AF7",
      base1: "#24273a",
      mantle: "#1e2030",
      crust: "#181926",
      text: "#cad3f5",
      subtext1: "#b8c0e0",
      subtext0: "#a5adcb",
      overlay2: "#939ab7",
      overlay1: "#8087a2",
      overlay0: "#6e738d",
      surface2: "#5b6078",
      surface1: "#494d64",
      surface0: "#363a4f",
      rosewater: "#f4dbd6",
      flamingo: "#f0c6c6",
      mauve: "#c6a0f6",
      maroon: "#ee99a0",
      peach: "#f5a97f",
      green1: "#a6da95",
      teal: "#8bd5ca",
      blue1: "#8aadf4",
      sky1: "#91d7e3",
      sapphire: "#7dc4e4",
      lavender: "#b7bdf8",
      red1: "#ed8796",


      black: colors.black,
      white: colors.white,
      gray: colors.gray,
      emerald: colors.emerald,
      indigo: colors.indigo,
      yellow: colors.yellow,
      slate: colors.slate,
      blue: colors.blue,
      purple: colors.purple,
      red: colors.red,
    },
  },
  plugins: [],
};
